version: '3.1'

services:
  appliances:
    build: ./appliances
    container_name: appliances
    ports:
      - 8081:3000
    expose:
      - 8081
    volumes:
      - ./appliances/src:/home/app/src
    command: npm run start

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    links:
      - appliances
